import { chromium } from '@playwright/test';
const R = Number(process.argv[2] ?? 14);
const b = await chromium.launch({ headless: true, channel: 'chrome', args: ['--use-angle=d3d11','--enable-unsafe-webgpu','--ignore-gpu-blocklist','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-features=CalculateNativeWinOcclusion'] });
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 } });
await ctx.addInitScript(() => { try { localStorage.setItem('atomic-acres-pass65-settings-v1', JSON.stringify({ version:1, graphics:{ schemaVersion:1, preset:'custom', weatherIntensity:'storm', rainDensity:1.5, windStrength:2, lightning:true, wetSurfaces:true, ambientLife:2 } })); } catch {} });
const page = await ctx.newPage();
const s = await page.context().newCDPSession(page); await s.send('Emulation.setFocusEmulationEnabled',{enabled:true}).catch(()=>{});
await page.goto('http://127.0.0.1:41917/?release=latest&renderer=webgpu&render=quality&seed=pass79weather&weather=storm', { waitUntil:'domcontentloaded' });
await page.waitForFunction(() => Boolean(window.__ATOMIC_ACRES_DEBUG__), undefined, { timeout: 240000 });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.startSolo(); });
await page.waitForFunction(() => { const s = window.__ATOMIC_ACRES_DEBUG__.snapshot(); return s.matchPhase==='active' && s.gameStarted===true; }, undefined, { timeout: 240000 });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.setBotsFrozen(true); });
const staged = await page.evaluate(() => window.__ATOMIC_ACRES_DEBUG__.placeBotAhead(9));
console.error('staged', JSON.stringify({ d: staged?.stagedDistanceM, bot: staged?.bot.logicalPosition, p: staged?.sourcePlayer.position }));
const info = await page.evaluate(({ staged, R }) => {
  const bot = staged.bot.logicalPosition, from = staged.sourcePlayer.position;
  const dx = from[0]-bot[0], dz = from[2]-bot[2], L = Math.hypot(dx,dz)||1;
  window.__ATOMIC_ACRES_DEBUG__.teleportPlayer(bot[0]+dx/L*R, from[1], bot[2]+dz/L*R);
  window.__ATOMIC_ACRES_DEBUG__.aimAtBot();
  return { target: [bot[0]+dx/L*R, from[1], bot[2]+dz/L*R] };
}, { staged, R });
await page.waitForTimeout(2500);
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.aimAtBot(); });
await page.waitForTimeout(1500);
console.error('pose', JSON.stringify(await page.evaluate(() => { const p = window.__ATOMIC_ACRES_DEBUG__.snapshot().player; return { pos: p.position.map(v=>+v.toFixed(2)), yaw:+p.yaw.toFixed(3), pitch:+p.pitch.toFixed(3), grounded:p.grounded }; })));
await page.screenshot({ path: `artifacts/pass79/weather/stance-${R}-with.png` });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.clearBots(); });
await page.waitForTimeout(900);
console.error('bots after clear', await page.evaluate(() => window.__ATOMIC_ACRES_DEBUG__.snapshot().arenaSelection?.soloBotCount ?? 'n/a'));
await page.screenshot({ path: `artifacts/pass79/weather/stance-${R}-without.png` });
await b.close();
