import { chromium } from '@playwright/test';
const W = process.argv[2] ?? 'storm';
const b = await chromium.launch({ headless: true, channel: 'chrome', args: ['--use-angle=d3d11','--enable-unsafe-webgpu','--ignore-gpu-blocklist','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-features=CalculateNativeWinOcclusion'] });
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 } });
await ctx.addInitScript(() => { try { localStorage.setItem('atomic-acres-pass65-settings-v1', JSON.stringify({ version:1, graphics:{ schemaVersion:1, preset:'custom', weatherIntensity:'storm', rainDensity:1.5, windStrength:2, lightning:true, wetSurfaces:true, ambientLife:2 } })); } catch {} });
const page = await ctx.newPage();
const s = await page.context().newCDPSession(page); await s.send('Emulation.setFocusEmulationEnabled',{enabled:true}).catch(()=>{});
await page.goto(`http://127.0.0.1:41917/?release=latest&renderer=webgpu&render=quality&seed=pass79weather&weather=${W}`, { waitUntil:'domcontentloaded' });
await page.waitForFunction(() => Boolean(window.__ATOMIC_ACRES_DEBUG__), undefined, { timeout: 240000 });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.startSolo(); });
await page.waitForFunction(() => { const s = window.__ATOMIC_ACRES_DEBUG__.snapshot(); return s.matchPhase==='active' && s.gameStarted===true; }, undefined, { timeout: 240000 });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.setBotsFrozen(true); });
const staged = await page.evaluate(() => { const r = window.__ATOMIC_ACRES_DEBUG__.placeBotAhead(9); window.__ATOMIC_ACRES_DEBUG__.aimAtBot(); return r; });
console.error('staged d=', staged?.stagedDistanceM, 'yawOffset=', staged?.yawOffsetRadians?.toFixed(3), 'bot=', staged?.bot.logicalPosition.map(v=>+v.toFixed(2)), 'alive=', staged?.bot.alive);
await page.waitForTimeout(3000);
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.aimAtBot(); });
await page.waitForTimeout(1200);
await page.screenshot({ path: `artifacts/pass79/weather/pair-${W}-with.png` });
await page.evaluate(() => { window.__ATOMIC_ACRES_DEBUG__.clearBots(); });
await page.waitForTimeout(1200);
await page.screenshot({ path: `artifacts/pass79/weather/pair-${W}-without.png` });
await b.close();
