#!/usr/bin/env node
/**
 * Convert the measured 512² derived PNGs into a deterministic source module.
 *
 * Runtime arena construction is synchronous, so the bridge cannot wait on a
 * browser ImageBitmap loader. Keeping the already-derived RGBA/R8 bytes in a
 * generated module gives the WebGPU graph the real image-generated maps at
 * construction time while the source PNGs remain available for inspection.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const output = path.join(root, 'src/nuketown2-materials/generated-texture-assets.ts');
const families = ['asphalt', 'lapSiding', 'brick', 'concrete', 'shingle', 'timber'];

async function readRaw(file, size, channels) {
  const image = sharp(file).resize({ width: size, height: size, fit: 'fill' });
  if (channels === 1) image.greyscale();
  const buffer = await image.raw().toBuffer();
  if (buffer.length !== size * size * channels) throw new Error(`${file} raw channel count mismatch`);
  return buffer.toString('base64');
}

const records = [];
for (const family of families) {
  const familyRoot = path.join(root, 'docs/forge/textures', family, 'candidate-01');
  const report = JSON.parse(await readFile(path.join(familyRoot, 'derive-report.json'), 'utf8'));
  const measured = report.resolutions.find((entry) => entry.size === 512);
  if (!measured || measured.wrapDelta > 1) throw new Error(`${family} has no passing 512 report`);
  const mapRoot = path.join(familyRoot, '512');
  records.push({
    family,
    size: 512,
    metresPerTile: measured.metresPerTile,
    source: report.input,
    fractionMostlyZ: measured.fractionMostlyZ,
    detail: measured.detail,
    albedo: await readRaw(path.join(mapRoot, 'albedo.png'), 512, 4),
    normal: await readRaw(path.join(mapRoot, 'normal.png'), 512, 4),
    roughness: await readRaw(path.join(mapRoot, 'roughness.png'), 512, 1),
  });
}

const lines = [
  '/** Generated by scripts/forge/texture-pipeline/embed-assets.mjs; do not hand edit. */',
  'export type Nuketown2ImageTextureAsset = Readonly<{',
  '  readonly size: 512;',
  '  readonly metresPerTile: number;',
  '  readonly source: string;',
  '  readonly fractionMostlyZ: number;',
  '  readonly detail: Readonly<Record<string, number>>;',
  '  readonly albedo: string;',
  '  readonly normal: string;',
  '  readonly roughness: string;',
  '}>;',
  'export const NUKETOWN2_IMAGE_TEXTURE_ASSETS = {',
];
for (const record of records) {
  lines.push(`  ${record.family}: Object.freeze(${JSON.stringify(record)}),`);
}
lines.push('} as const satisfies Readonly<Record<string, Nuketown2ImageTextureAsset>>;');
lines.push('');
await writeFile(output, `${lines.join('\n')}\n`, 'utf8');
console.log(JSON.stringify({ output: path.relative(root, output).replaceAll('\\', '/'), families, bytes: (await readFile(output)).length }, null, 2));
