#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import {
  PASS65_ADVANCED_GRAPHICS_TRACE,
  PASS65_RENDERER_FEATURES,
  pass65RendererFeatureInventoryReport,
  validatePass65RendererFeatureInventory,
  type RendererFeatureDefinition,
} from '../../src/pass65-renderer-feature-inventory';

const repositoryRoot = resolve(import.meta.dirname, '..', '..');
const jsonPath = resolve(repositoryRoot, 'docs', 'PASS65_RENDERER_FEATURE_INVENTORY.generated.json');
const markdownPath = resolve(repositoryRoot, 'docs', 'PASS65_RENDERER_FEATURE_INVENTORY.generated.md');

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

function cell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll(/\s+/g, ' ').trim();
}

function markdownFeature(feature: RendererFeatureDefinition): string {
  const settings = feature.control.settingKeys.length > 0 ? feature.control.settingKeys.join(', ') : '—';
  return `| ${feature.id} | ${feature.availability} | ${feature.control.kind} | ${cell(settings)} | ${cell(feature.control.effectiveValue)} | ${cell(feature.control.rationale)} | ${cell(feature.budget)} |`;
}

function markdownSettingTrace(setting: ReturnType<typeof pass65RendererFeatureInventoryReport>['settings'][number]): string {
  const evidence = setting.runtimeEvidence?.map(({ path, symbol }) => `${path} :: ${symbol}`).join('<br>') ?? 'MISSING';
  const telemetry = setting.runtimeEvidence?.map(({ telemetryPath }) => telemetryPath).join('<br>') ?? 'MISSING';
  return `| ${setting.key} | ${setting.runtimeConsumer ?? 'MISSING'} | ${cell(evidence)} | ${cell(telemetry)} |`;
}

function markdownReport(report: ReturnType<typeof pass65RendererFeatureInventoryReport>, inventorySha256: string): string {
  const profileRows = Object.entries(report.profiles).map(([name, snapshot]) => (
    `| ${name} | ${snapshot.effective.renderProfile} | ${snapshot.effective.renderScale} | ${snapshot.effective.adaptive} | ${snapshot.effective.shadows} | ${snapshot.effects.tier} |`
  )).join('\n');
  return `# Pass 65 Renderer Feature Inventory (generated)

Candidate: **${report.releasePass} · ${report.candidateName}**

Inventory SHA-256: \`${inventorySha256}\`

This file is generated by \`${report.generatedBy}\`. It describes the current implementation, including missing controls; it is not a claim that every planned graphics option is complete.

## Advanced Graphics end-to-end trace

Every player-visible graphics setting follows the same checked chain: registry \`${report.advancedGraphicsTrace.registry.path}\` → generated UI \`${report.advancedGraphicsTrace.ui.path}\` → normalization \`${report.advancedGraphicsTrace.normalization.path}\` → read-back-verified persistence \`${report.advancedGraphicsTrace.persistence.path}\` → the setting-specific runtime source below → debug telemetry rooted at \`${report.advancedGraphicsTrace.telemetry.symbol}\`.

| Setting | Runtime consumer | Runtime source probe | Effective telemetry evidence |
|---|---|---|---|
${report.settings.filter(({ key }) => key.startsWith('graphics.')).map(markdownSettingTrace).join('\n')}

## Effective preset summary

| Preset | Render profile | Scale | Adaptive | Shadows | Effects tier |
|---|---|---:|---:|---:|---|
${profileRows}

## Feature-to-setting or rationale map

| Feature | Availability | Control | Setting keys | Effective value | Rationale | Budget |
|---|---|---|---|---|---|---|
${report.features.map(markdownFeature).join('\n')}

## Truthful gaps

${report.features.filter(({ availability }) => availability === 'unsupported').map((feature) => `- **${feature.title}:** ${feature.control.rationale}`).join('\n')}

## Summary

- Total inventoried features: ${report.summary.total}
- Active: ${report.summary.active}
- Unsupported and explicitly reported: ${report.summary.unsupported}
- Player-adjustable through a setting or preset: ${report.summary.adjustable}
- Fixed with an explicit rationale: ${report.summary.fixedWithRationale}
`;
}

function generatedBytes() {
  const report = pass65RendererFeatureInventoryReport();
  const inventorySha256 = sha256(JSON.stringify(report.features));
  const json = `${JSON.stringify({ ...report, inventorySha256 }, null, 2)}\n`;
  const markdown = markdownReport(report, inventorySha256);
  return { json, markdown, inventorySha256 };
}

const issues = [...validatePass65RendererFeatureInventory()];
for (const [stage, probe] of Object.entries(PASS65_ADVANCED_GRAPHICS_TRACE)) {
  const path = resolve(repositoryRoot, probe.path);
  if (!existsSync(path)) issues.push(`missing-trace-source:${stage}:${probe.path}`);
  else if (!readFileSync(path, 'utf8').includes(probe.symbol)) issues.push(`missing-trace-symbol:${stage}:${probe.path}:${probe.symbol}`);
}
for (const setting of pass65RendererFeatureInventoryReport().settings.filter(({ key }) => key.startsWith('graphics.'))) {
  for (const probe of setting.runtimeEvidence ?? []) {
    const path = resolve(repositoryRoot, probe.path);
    if (!existsSync(path)) issues.push(`missing-setting-source:${setting.key}:${probe.path}`);
    else if (!readFileSync(path, 'utf8').includes(probe.symbol)) issues.push(`missing-setting-symbol:${setting.key}:${probe.path}:${probe.symbol}`);
  }
}
for (const feature of PASS65_RENDERER_FEATURES) {
  for (const probe of feature.sourceProbes) {
    const path = resolve(repositoryRoot, probe.path);
    if (!existsSync(path)) issues.push(`missing-source:${feature.id}:${probe.path}`);
    else if (!readFileSync(path, 'utf8').includes(probe.symbol)) issues.push(`missing-symbol:${feature.id}:${probe.path}:${probe.symbol}`);
  }
}
if (issues.length > 0) throw new Error(`Renderer feature inventory is invalid:\n${issues.join('\n')}`);

const generated = generatedBytes();
if (process.argv.includes('--check')) {
  for (const [path, expected] of [[jsonPath, generated.json], [markdownPath, generated.markdown]] as const) {
    if (!existsSync(path)) throw new Error(`Generated renderer inventory is missing: ${path}`);
    if (readFileSync(path, 'utf8') !== expected) throw new Error(`Generated renderer inventory is stale: ${path}`);
  }
  console.log(JSON.stringify({ rendererFeatureInventory: 'verified', inventorySha256: generated.inventorySha256 }));
} else {
  mkdirSync(dirname(jsonPath), { recursive: true });
  writeFileSync(jsonPath, generated.json, 'utf8');
  writeFileSync(markdownPath, generated.markdown, 'utf8');
  console.log(JSON.stringify({ rendererFeatureInventory: 'generated', inventorySha256: generated.inventorySha256 }));
}
