/**
 * HF-491 perf lane (HITL 5): the shared noise LUT behind every Nuke Town wear
 * graph. It replaced per-fragment lattice noise on fifty node materials, so
 * the properties that made the shader version correct are pinned here on the
 * generated bytes: it is GENERATED (no file, no fetch), it is ONE shared
 * instance, it TILES seamlessly, and each channel carries the octave count its
 * consumer expects.
 */
import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import * as TSL from 'three/tsl';

import {
  NOISE_LUT_CELLS,
  NOISE_LUT_SIZE,
  generateNoiseLutData,
  noiseLutTexture,
  resetNoiseLutForTests,
} from './noise-lut';
import { NOISE_TILE_CELLS, signedNoise } from './wear';

const { vec2 } = TSL as unknown as Record<string, any>;

describe('nuketown2 noise LUT', () => {
  it('is generated on the CPU, never loaded: one shared DataTexture with in-memory bytes', () => {
    resetNoiseLutForTests();
    const first = noiseLutTexture();
    expect(noiseLutTexture(), 'second ask returns the same tile').toBe(first);
    expect(first).toBeInstanceOf(THREE.DataTexture);
    expect(first.image.width).toBe(NOISE_LUT_SIZE);
    expect(first.image.height).toBe(NOISE_LUT_SIZE);
    expect(first.image.data).toBeInstanceOf(Uint8Array);
    expect((first.image as { src?: string }).src ?? null, 'no URL: nothing is fetched').toBeNull();
    expect(first.wrapS).toBe(THREE.RepeatWrapping);
    expect(first.wrapT).toBe(THREE.RepeatWrapping);
    expect(first.colorSpace).toBe(THREE.NoColorSpace);
    expect(first.flipY).toBe(false);
  });

  it('is deterministic', () => {
    const a = generateNoiseLutData(32, 8);
    const b = generateNoiseLutData(32, 8);
    expect(Array.from(a)).toEqual(Array.from(b));
  });

  it('tiles: the wrap seam is as smooth as any interior step', () => {
    // A lattice whose period is not an integer number of cells shows a hard
    // line at the tile edge under RepeatWrapping; that line is what the shader
    // version's integer-period rule prevented and this pins the same rule on
    // the baked bytes. Compare the seam step (last column -> first column)
    // against the largest interior step per channel.
    const size = 128;
    const data = generateNoiseLutData(size, 16);
    for (let channel = 0; channel < 4; channel += 1) {
      let seam = 0;
      let interior = 0;
      for (let y = 0; y < size; y += 1) {
        const row = y * size * 4;
        seam = Math.max(seam, Math.abs(data[row + channel]! - data[row + (size - 1) * 4 + channel]!));
        for (let x = 1; x < size; x += 1) {
          interior = Math.max(interior, Math.abs(data[row + x * 4 + channel]! - data[row + (x - 1) * 4 + channel]!));
        }
      }
      expect(seam, `channel ${channel} horizontal seam`).toBeLessThanOrEqual(interior);
    }
  });

  it('carries more detail in each successive octave channel', () => {
    // Local extrema per row grow with octave count: one octave of smoothstep
    // value noise turns at most once per lattice cell, each added octave adds
    // its own turns. R (one octave) is the smoothest, B (three) the busiest.
    // A (ridged) is a different shape, so it is only required to be non-flat.
    const size = 128;
    const data = generateNoiseLutData(size, 16);
    const turns = (channel: number): number => {
      let count = 0;
      for (let y = 0; y < size; y += 1) {
        let lastSign = 0;
        for (let x = 1; x < size; x += 1) {
          const i = (y * size + x) * 4 + channel;
          const sign = Math.sign(data[i]! - data[i - 4]!);
          if (sign === 0) continue;
          if (lastSign !== 0 && sign !== lastSign) count += 1;
          lastSign = sign;
        }
      }
      return count;
    };
    const r = turns(0);
    const g = turns(1);
    const b = turns(2);
    expect(g).toBeGreaterThan(r);
    expect(b).toBeGreaterThan(g);
    expect(turns(3)).toBeGreaterThan(0);
    // And every channel actually spans a usable range.
    for (let channel = 0; channel < 4; channel += 1) {
      let min = 255; let max = 0;
      for (let i = channel; i < data.length; i += 4) { min = Math.min(min, data[i]!); max = Math.max(max, data[i]!); }
      expect(max - min, `channel ${channel} dynamic range`).toBeGreaterThan(100);
    }
  });

  it('is the tile the wear engine samples', () => {
    expect(NOISE_TILE_CELLS).toBe(NOISE_LUT_CELLS);
    // signedNoise still builds a node expression (the arena builds materials
    // headless in tests), and it does so without touching per-fragment fBm.
    const node = signedNoise(vec2(1.5, 2.5), 0.001, 2);
    expect(node).toBeTruthy();
  });
});
