export type {
  EavesFrameOptions,
  EavesPart,
  EavesPipeSpec,
  EavesRole,
  EavesRunOptions,
  GarageGutterKit,
  GarageGutterOptions,
} from './prefabs';
export {
  EAVES_BRACKET_END_INSET,
  EAVES_BRACKET_H,
  EAVES_BRACKET_SPACING,
  EAVES_BRACKET_W,
  EAVES_DRIP_D,
  EAVES_DRIP_H,
  EAVES_FASCIA_H,
  EAVES_FASCIA_PROUD,
  EAVES_FASCIA_T,
  EAVES_GARAGE_BOXES,
  EAVES_GARAGE_PIPES,
  EAVES_GARAGE_TRIANGLES,
  EAVES_GUTTER_DROP,
  EAVES_GUTTER_H,
  EAVES_GUTTER_PROUD,
  EAVES_GUTTER_W,
  EAVES_HOUSE_BOXES,
  EAVES_HOUSE_TRIANGLES,
  EAVES_PIPE_R,
  EAVES_PIPE_SEGMENTS,
  EAVES_PIPE_STANDOFF_MIN,
  EAVES_PIPE_TRIANGLES,
  EAVES_SHOE_BASE_Y,
  EAVES_SHOE_H,
  EAVES_SOFFIT_DROP,
  EAVES_SOFFIT_T,
  EAVES_TRIS_PER_BOX,
  eavesBandOuter,
  eavesBracketXs,
  fasciaLength,
  fasciaParts,
  garageGutterParts,
  houseRetroBracketParts,
  soffitParts,
} from './prefabs';
