import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectConnectedSample,validNaturalLife,evaluateMpSoakV2,V2_PEERS} from './mp-soak-v2-contract.mjs';
const identities={host:'h',guestA:'a',guestB:'b'};
const player=(life=1,hp=100)=>({position:[0,1.7,0],authoritativePosition:[0,1.7,0],continuity:life,hp,alive:hp>0,weapon:'rifle',primary:'rifle',ammo:30,reserve:90});
function views(){return Object.fromEntries(V2_PEERS.map(role=>[role,{selfId:identities[role],remotes:2,gameStarted:true,matchPhase:'active',players:Object.fromEntries(Object.values(identities).map(id=>[id,player()])),lobby:{revision:4,members:Object.values(identities).map(id=>({id,connected:true}))}}]));}
const life=()=>({manualRespawn:false,applied:{storedBefore:100,storedAfter:0},before:Object.fromEntries(V2_PEERS.map(r=>[r,player()])),dead:Object.fromEntries(V2_PEERS.map(r=>[r,player(1,0)])),after:Object.fromEntries(V2_PEERS.map(r=>[r,player(2)]))});
function health(){
  const row=(stage,atMs,observedHp=null)=>({stage,atMs,timeOriginMs:1000,subjectId:'b',authorId:'h',revision:7,continuity:4,matchEpoch:2,hp:80,observedHp,reason:stage==='admit'?'accepted':null});
  const clock=now=>({now,origin:1000,date:1000+now,nodeBefore:1000+now,nodeAfter:1000+now});
  return{completed:true,nodeTriggeredAt:2000,subjectId:'b',trigger:{before:1000,after:1001,origin:1000,applied:{storedBefore:100,storedAfter:80}},calibration:{before:{guestA:[clock(990)],guestB:[clock(990)]},after:{guestA:[clock(1300)],guestB:[clock(1300)]}},peers:{host:{trace:{enabled:true,dropped:0,rows:[row('publish',1000,80)]}},...Object.fromEntries(['guestA','guestB'].map(r=>[r,{trace:{enabled:true,dropped:0,rows:[row('receive',1100),row('admit',1100,100),row('apply',1100,80)]}}]))}};
}
function fixture(){return{contract:'mp-soak-gate-v2',sourceSha:'a'.repeat(40),completed:true,identities:{...identities},config:{playDurationMs:180000,sampleIntervalMs:1000,positionBoundM:1.5,rttMs:120,packetLossPct:1,hardTimeoutMs:299000},timing:{playDurationMs:200000},replication:{samples:Array.from({length:180},(_,i)=>({atEpochMs:i*1000,peers:views(),identities:{...identities}})),divergences:[],pairDirections:Object.fromEntries(V2_PEERS.flatMap(a=>V2_PEERS.filter(b=>a!==b).map(b=>[`${a}->${b}`,true])))},lifecycle:{transition:{role:'guestB',identityBefore:'b',identityAfter:'b',beforeRevision:4,intentAt:180000,joinAt:183000,settledAt:184000,leave:Object.fromEntries(['host','guestA'].map(r=>[r,{disconnected:true,atEpochMs:181000,revision:5}])),settled:Object.fromEntries(V2_PEERS.map(r=>[r,{remotes:2,connectedIds:['h','a','b']}]))},samples:[{atEpochMs:181000,peers:views(),identities:{...identities}}]},rejoin:{role:'guestB',leaveObserved:true,rejoinObserved:true,seenByEveryoneAfter:true,damage:{triggered:true,maxLatencyMs:101,report:health()}},scenarios:{guests:Object.fromEntries(['guestA','guestB'].map(r=>[r,{reloadAfterDeath:true,respawnLoadoutReset:true,stairFire:true,naturalLife:life()}]))},consoleErrors:{host:[],guestA:[],guestB:[]},scoreboard:{agreement:true,host:[],guestA:[],guestB:[]},liveArtifact:Object.fromEntries(V2_PEERS.map(r=>[r,{backend:'webgpu',indexMatches:true,mainMatches:true}]))};}
test('complete explicit v2 fixture passes all unchanged numeric requirements',()=>assert.equal(evaluateMpSoakV2(fixture()).pass,true));
test('all six connected directions are measured',()=>assert.equal(inspectConnectedSample(views(),identities).directions.length,6));
test('connected omission fails',()=>{const v=views();delete v.guestA.players.b;assert.equal(inspectConnectedSample(v,identities).pass,false);});
test('intentional B leave does not excuse unrelated A loss',()=>{const v=views();delete v.host.players.a;assert.equal(inspectConnectedSample(v,identities,['host','guestA']).pass,false);});
test('wrong active identity fails',()=>{const v=views();v.guestB.selfId='other';assert.equal(inspectConnectedSample(v,identities).pass,false);});
test('duplicate identity or incomplete remote world fails',()=>{assert.equal(inspectConnectedSample(views(),{host:'h',guestA:'h',guestB:'b'}).pass,false);const v=views();v.guestB.remotes=1;assert.equal(inspectConnectedSample(v,identities).pass,false);});
test('over1.5m still fails',()=>{const v=views();v.guestA.players.h.position[0]=1.5001;assert.equal(inspectConnectedSample(v,identities).pass,false);});
test('179 connected samples fail despite200 lifecycle rows',()=>{const f=fixture();f.replication.samples.pop();f.lifecycle.samples=Array.from({length:200},()=>f.lifecycle.samples[0]);assert.equal(evaluateMpSoakV2(f).pass,false);});
test('catch-up sampling bursts fail',()=>{const f=fixture();f.replication.samples[3].atEpochMs=2001;assert.equal(evaluateMpSoakV2(f).pass,false);});
test('a missing directed pair fails',()=>{const f=fixture();delete f.replication.pairDirections['guestA->guestB'];assert.equal(evaluateMpSoakV2(f).pass,false);});
test('never-rejoin and wrong rejoin identity fail',()=>{for(const mutation of[t=>{delete t.settledAt;},t=>{t.identityAfter='other';},t=>{t.leave.host.revision=3;}]){const f=fixture();mutation(f.lifecycle.transition);assert.equal(evaluateMpSoakV2(f).pass,false);}});
test('unexpected disconnect in full coverage fails even if driver divergences array is empty',()=>{const f=fixture();f.replication.samples[12].peers.host.lobby.members[1].connected=false;assert.equal(evaluateMpSoakV2(f).pass,false);});
test('unobserved death cannot qualify',()=>{const r=life();delete r.dead.guestA;assert.equal(validNaturalLife(r),false);});
test('already alive manual respawn cannot qualify',()=>{const r=life();r.manualRespawn=true;assert.equal(validNaturalLife(r),false);});
test('same life and discordant new life cannot qualify',()=>{for(const n of[1,3]){const r=life();r.after.guestA.continuity=n;assert.equal(validNaturalLife(r),false);}});
test('weakened config cannot qualify',()=>{const f=fixture();f.config.positionBoundM=99;assert.equal(evaluateMpSoakV2(f).pass,false);});
test('missing or delayed real apply cannot be replaced by a stored PASS claim',()=>{for(const delayed of[false,true]){const f=fixture();f.rejoin.damage.measurement={verdict:'PASS',boundMs:120};if(delayed)f.rejoin.damage.report.peers.guestA.trace.rows.at(-1).atMs=1200;else f.rejoin.damage.report.peers.guestA.trace.rows.pop();assert.equal(evaluateMpSoakV2(f).pass,false);}});
