/**
 * HF-376 - source synthesis for the sound families that made the owner say
 * "the sounds are all so bad".
 *
 * WHY THIS EXISTS
 * The immersion layer (audio-immersion.ts, HF-366) answers "how does this
 * sound from over there": distance lowpass, occlusion duck, indoor tails. It
 * was landed and the owner still said the sounds were bad, which localises the
 * remaining fault to the SOURCE: every voice in the game was one oscillator or
 * one band of noise whose amplitude went
 *
 *     setValueAtTime(peak) -> exponentialRampToValueAtTime(0)
 *
 * An instantaneous attack into a single exponential decay is the definition of
 * a synth beep. Real gunfire, explosions and impacts have three distinct
 * temporal regions - a transient of a couple of milliseconds, a body that
 * collapses fast and then holds, and a tail that outlives both - plus a pitch
 * contour that falls far faster at the start than a single exponential ramp
 * does, and harmonic content generated by non-linearity rather than by the
 * oscillator's own waveform.
 *
 * This module is the missing synthesis vocabulary, kept PURE so it is testable
 * without an AudioContext: noise textures, a saturation transfer curve, the
 * three-region amplitude envelope, and the front-loaded pitch fall. audio.ts
 * schedules the stages these functions return onto real AudioParams.
 *
 * EVERYTHING HERE IS PROCEDURAL. Textures are generated from a caller-supplied
 * random source at unlock time; no sampled or licensed audio enters the
 * project, which is a hard repository rule.
 */

/**
 * Noise characters the runtime can draw a burst from. One shared white buffer
 * had to serve gunfire, explosions, footsteps and debris, which is why a
 * shotgun and a boot on gravel shared a spectrum.
 */
export const NOISE_TEXTURES = Object.freeze([
  /** Near-flat spectrum. Air, muzzle transients, steam. */
  'white',
  /** -3 dB/octave. The natural spectrum of distant reports and room tails. */
  'pink',
  /** -6 dB/octave. Blast weight, heavy body thumps, boots on soft ground. */
  'brown',
  /** Sparse decaying impulses. Debris patter, shell casings, glass, gravel. */
  'crackle',
  /** Amplitude-modulated and soft-clipped. Scuffs, cloth, mechanical rasp. */
  'grit',
] as const);

export type NoiseTexture = (typeof NOISE_TEXTURES)[number];

/**
 * Writes one noise texture into `data` in place and normalises it to just under
 * full scale, so a caller can swap texture without re-balancing its gain.
 *
 * `random` must return [0, 1). It is a parameter rather than Math.random so the
 * runtime can feed its seeded presentation stream and tests can feed a fixture.
 */
export function fillNoiseTexture(
  data: Float32Array,
  texture: NoiseTexture,
  random: () => number,
): void {
  const length = data.length;
  if (length === 0) return;

  if (texture === 'white') {
    // The historical recipe: a one-pole tilt that takes the hardest edge off
    // white without darkening it. Preserved so voices that do not ask for a
    // texture sound exactly as they did before this pass.
    let previous = 0;
    for (let index = 0; index < length; index += 1) {
      previous = previous * 0.16 + (random() * 2 - 1) * 0.84;
      data[index] = previous;
    }
  } else if (texture === 'pink') {
    // Paul Kellet's economical pink filter: six one-poles summed. -3 dB/octave
    // is what a report sounds like after a few tens of metres of air, and what
    // a room tail decays as.
    let b0 = 0; let b1 = 0; let b2 = 0; let b3 = 0; let b4 = 0; let b5 = 0; let b6 = 0;
    for (let index = 0; index < length; index += 1) {
      const white = random() * 2 - 1;
      b0 = 0.99886 * b0 + white * 0.0555179;
      b1 = 0.99332 * b1 + white * 0.0750759;
      b2 = 0.96900 * b2 + white * 0.1538520;
      b3 = 0.86650 * b3 + white * 0.3104856;
      b4 = 0.55000 * b4 + white * 0.5329522;
      b5 = -0.7616 * b5 - white * 0.0168980;
      data[index] = b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362;
      b6 = white * 0.115926;
    }
  } else if (texture === 'brown') {
    // A leaky integrator. The leak matters: a pure integrator random-walks into
    // subsonic DC that costs headroom and moves no speaker cone.
    let previous = 0;
    for (let index = 0; index < length; index += 1) {
      previous = previous * 0.985 + (random() * 2 - 1) * 0.06;
      data[index] = previous;
    }
  } else if (texture === 'crackle') {
    // Sparse impulses with individual exponential decays. This is what makes
    // debris read as many small pieces rather than as one filtered whoosh, and
    // it is the difference between "gravel" and "noise burst" underfoot.
    data.fill(0);
    let amplitude = 0;
    let decay = 0.4;
    for (let index = 0; index < length; index += 1) {
      if (random() < 0.006) {
        amplitude = (random() * 2 - 1) * (0.35 + random() * 0.65);
        // Each grain gets its own decay, so the texture has a grain-size
        // distribution instead of one repeated click shape.
        decay = 0.45 + random() * 0.5;
      }
      data[index] = amplitude;
      amplitude *= decay;
    }
  } else {
    // grit: white modulated by a slow random envelope, then soft-clipped. The
    // modulation gives it the uneven, rubbing quality a scuff or a dry
    // mechanical part has; the clip adds the harmonics that make it read as
    // friction rather than as hiss.
    let envelope = 0.5;
    let previous = 0;
    for (let index = 0; index < length; index += 1) {
      envelope += ((random() * 0.9 + 0.1) - envelope) * 0.004;
      previous = previous * 0.35 + (random() * 2 - 1) * 0.65;
      data[index] = Math.tanh(previous * envelope * 2.6);
    }
  }

  let peak = 0;
  for (let index = 0; index < length; index += 1) {
    const magnitude = Math.abs(data[index]!);
    if (magnitude > peak) peak = magnitude;
  }
  if (peak <= 0) return;
  const scale = 0.98 / peak;
  for (let index = 0; index < length; index += 1) data[index] = data[index]! * scale;
}

/**
 * WaveShaper transfer curve. Saturation is what separates a loud gunshot from a
 * quiet gunshot with the volume turned up: clipping the peaks lets the body sit
 * far higher in the mix at the same peak level, and the harmonics it generates
 * are the "crack" a listener localises the weapon by.
 *
 * `drive` in [0, 1]. 0 is a straight wire; the curve stays monotonic and
 * bounded in [-1, 1] at every drive so it can never invert or fold the signal.
 */
export function saturationCurve(drive: number, samples = 1_024): Float32Array<ArrayBuffer> {
  const clampedDrive = Number.isFinite(drive) ? Math.min(1, Math.max(0, drive)) : 0;
  const count = Math.max(2, Math.floor(samples));
  const curve = new Float32Array(count);
  // 1 -> a wire, 12 -> hard-knee clipping. Exponential so the low half of the
  // control range is usable rather than inaudible.
  const knee = 1 + clampedDrive * clampedDrive * 11;
  const normalise = Math.tanh(knee);
  for (let index = 0; index < count; index += 1) {
    const x = (index / (count - 1)) * 2 - 1;
    const shaped = Math.tanh(knee * x) / normalise;
    // Blended against the identity rather than used raw, so drive 0 is exactly
    // a wire. tanh(x)/tanh(1) is already audibly compressive, which would mean
    // every voice routed through a saturator got coloured whether it asked for
    // it or not. Both terms are monotonic and land on +/-1 at the edges, so the
    // blend inherits both guarantees.
    curve[index] = x + (shaped - x) * clampedDrive;
  }
  return curve;
}

export type EnvelopeRamp = 'linear' | 'exponential';

export type EnvelopeStage = Readonly<{
  /** Seconds after the voice's own start time. */
  atSeconds: number;
  value: number;
  ramp: EnvelopeRamp;
}>;

export type TransientEnvelopeSpec = Readonly<{
  peak: number;
  durationSeconds: number;
  /**
   * Seconds to reach peak. Never 0: a discontinuous onset is a DC step, which
   * is heard as a click on top of the sound rather than as part of it. Under
   * about 2 ms it still reads as instantaneous.
   */
  attackSeconds?: number;
  /**
   * Level the body settles to as a fraction of peak, after the initial
   * collapse. 1 reproduces the old single-exponential decay.
   */
  punch?: number;
  /** Seconds the initial collapse takes. */
  punchSeconds?: number;
  /** Silence floor; exponential ramps cannot reach or cross zero. */
  floorValue?: number;
}>;

/**
 * The three-region amplitude contour: attack, fast collapse to a held body,
 * long decay. Returned as stages so the caller can schedule them on any
 * AudioParam, and so the shape is assertable without an audio graph.
 *
 * Times are strictly increasing and every value is strictly positive, which are
 * exactly the preconditions WebAudio's exponential ramps require.
 */
export function transientEnvelope(spec: TransientEnvelopeSpec): readonly EnvelopeStage[] {
  const floorValue = Math.max(1e-5, spec.floorValue ?? 1e-4);
  const peak = Math.max(floorValue * 1.01, Number.isFinite(spec.peak) ? spec.peak : floorValue);
  const duration = Math.max(0.004, Number.isFinite(spec.durationSeconds) ? spec.durationSeconds : 0.004);
  // The attack and the collapse together may never consume the whole voice, or
  // the decay would have no time left and the sound would end on a step.
  const attack = Math.min(Math.max(0.0003, spec.attackSeconds ?? 0.0009), duration * 0.4);
  const punch = Math.min(1, Math.max(0.02, spec.punch ?? 1));
  const stages: EnvelopeStage[] = [
    { atSeconds: 0, value: floorValue, ramp: 'linear' },
    { atSeconds: attack, value: peak, ramp: 'linear' },
  ];
  if (punch < 1) {
    const punchSeconds = Math.min(
      Math.max(0.002, spec.punchSeconds ?? duration * 0.18),
      (duration - attack) * 0.6,
    );
    stages.push({
      atSeconds: attack + punchSeconds,
      value: Math.max(floorValue * 1.005, peak * punch),
      ramp: 'exponential',
    });
  }
  stages.push({ atSeconds: duration, value: floorValue, ramp: 'exponential' });
  return Object.freeze(stages);
}

export type FrequencyStage = Readonly<{ atSeconds: number; hz: number }>;

/**
 * Front-loaded frequency contour between two endpoints.
 *
 * A single exponentialRampToValueAtTime spends half its time in the top half of
 * the interval, which is why every sweep in this game read as a "boop": the ear
 * hears a slow glide and localises a pitch. Real bodies drop most of their
 * interval in the first fifth of their length and then settle, which is heard
 * as a thump with a pitch rather than as a pitch that moves.
 *
 * Endpoints are preserved exactly, so this is a drop-in for a single ramp.
 * `bias` in (0, 1) is how much of the (log) interval is spent before the knee -
 * higher is more front-loaded.
 */
export function pitchFallStages(
  startHz: number,
  endHz: number,
  durationSeconds: number,
  bias = 0.55,
): readonly FrequencyStage[] {
  const start = Math.max(1, Number.isFinite(startHz) ? startHz : 1);
  const end = Math.max(1, Number.isFinite(endHz) ? endHz : 1);
  const duration = Math.max(0.001, Number.isFinite(durationSeconds) ? durationSeconds : 0.001);
  const clampedBias = Math.min(0.9, Math.max(0.1, bias));
  // Degenerate interval: a knee would be indistinguishable from the endpoints,
  // and emitting one would only cost an automation event.
  if (Math.abs(Math.log(start / end)) < 1e-3) {
    return Object.freeze([{ atSeconds: duration, hz: end }]);
  }
  const kneeSeconds = duration * (1 - clampedBias) * 0.42;
  const kneeHz = end * Math.pow(start / end, 1 - clampedBias);
  return Object.freeze([
    { atSeconds: kneeSeconds, hz: kneeHz },
    { atSeconds: duration, hz: end },
  ]);
}

/**
 * Inharmonic partial ratios for struck metal. A harmonic series is heard as a
 * musical note; real plates and tubes ring on ratios that share no small
 * integer relationship, which is what makes a hit read as "metal" rather than
 * as "a tone". Used by impacts, shell ejection and rigging clinks.
 */
export const METALLIC_PARTIAL_RATIOS: readonly number[] = Object.freeze([1, 2.41, 3.83, 5.17]);

/**
 * Round-robin detune in cents. Two identical shots in a row is the single most
 * obvious "this is a synth" tell at automatic fire rates, and the cheapest fix
 * is per-shot variation that never repeats over a short window.
 */
export function roundRobinDetune(index: number, spreadCents = 55): number {
  const table = [0, 0.62, -0.38, 0.91, -0.77, 0.24, -0.95, 0.51];
  const value = table[((index % table.length) + table.length) % table.length]!;
  return value * spreadCents;
}

/** Multiplier for a detune expressed in cents. */
export function centsToRatio(cents: number): number {
  return Math.pow(2, (Number.isFinite(cents) ? cents : 0) / 1_200);
}
